export const permissionsOptions = [
  { label: "View Customers", value: "view_customers" },
  { label: "Create Customers", value: "create_customers" },
  { label: "Edit Customers", value: "edit_customers" },
  { label: "Delete Customers", value: "delete_customers" },
  { label: "View Employees", value: "view_employees" },
  { label: "Create Employees", value: "create_employees" },
  { label: "Edit Employees", value: "edit_employees" },
  { label: "Delete Employees", value: "delete_employees" },
  { label: "View Sellers", value: "view_sellers" },
  { label: "Create Sellers", value: "create_sellers" },
  { label: "Edit Sellers", value: "edit_sellers" },
  { label: "Delete Sellers", value: "delete_sellers" },
  { label: "View Orders", value: "view_orders" },
  { label: "Create Orders", value: "create_orders" },
  { label: "Edit Orders", value: "edit_orders" },
  { label: "Delete Orders", value: "delete_orders" },
  { label: "View Reports", value: "view_reports" },
  { label: "Generate Reports", value: "generate_reports" },
  { label: "View Products", value: "view_products" },
  { label: "Create Products", value: "create_products" },
  { label: "Edit Products", value: "edit_products" },
  { label: "Delete Products", value: "delete_products" },
  { label: "Manage Permissions", value: "manage_permissions" },
];